/** @license MIT License (c) copyright B Cavalier & J Hann *//**
 * wire/aop plugin
 * Provides AOP for components created via wire, including Decorators,
 * Introductions (mixins), and Pointcut-based Aspect Weaving.
 *
 * wire is part of the cujo.js family of libraries (http://cujojs.com/)
 *
 * Licensed under the MIT License at:
 * http://www.opensource.org/licenses/mit-license.php
 */define(["require","aop","when"],function(a,b,c){function l(a,b,c){c=c?[a].concat(c):[a],b.apply(null,c)}function m(a,b,d,e){function f(b){return d?c(e(d),function(c){l(a,b,c)}):l(a,b)}return c(e.resolveRef(b),f)}function n(a,b,c){var d,e,f;d=b.target,e=b.options,f=[];for(var g in e)f.push(m(d,g,e[g],c));i(h(f),a)}function o(a,b){var c,d;for(c in b){d=b[c];if(!(c in a)||a[c]!==d&&(!(c in e)||e[c]!==d))a[c]=d}return a}function p(a,b,d){return c(d.resolveRef(b),function(b){return o(a,b)})}function q(a,b,d){var e,f;e=b.target,f=b.options,g(f)||(f=[f]),i(c.reduce(f,function(a,b){return p(a,b,d)},e),a)}function r(a,b,d,e){return c(d.resolveRef(b),function(b){var c=b.pointcut;return c&&e(a,c,b),a})}function s(a,b,d,e){function h(b){return c(d.resolveRef(g),function(c){return e(a,b,c),a})}var f,g;return f=b.pointcut,g=b.advice,typeof f=="string"?c(d.resolveRef(f,h)):h(f)}function t(a,b,d,e,f){var g,h,j,l;j=e.aspects,h=b.path;if(!j||h===k){a.resolve();return}g=b.target,l=r,i(c.reduce(j,function(a,b){var c;return b.advice?(c=b.advice,l=s):c=b,typeof c=="string"&&c!==h?l(a,b,d,f):a},g),a)}var d,e,f,g,h,i,j,k;return d=Array.prototype,e={},f=Object.prototype.toString,g=Array.isArray||function(a){return f.call(a)=="[object Array]"},h=c.all,i=c.chain,j=c.defer,{wire$plugin:function(a,d,e){function g(a,c,d){f.push(b.add(a,c,d))}function h(a,b){var c={};return c[a]=function(a,c,d){b(a,c,d)},c}var f=[];return c(d,function(){for(var a=f.length;a>=0;--a)f[a].remove()}),{facets:{decorate:h("configure",n),introduce:h("configure",q)},create:function(a,b,c){t(a,b,c,e,g)}}}}});