/** @license MIT License (c) copyright B Cavalier & J Hann *//**
 * aop
 * Aspect Oriented Programming for Javascript
 *
 * aop is part of the cujo.js family of libraries (http://cujojs.com/)
 *
 * Licensed under the MIT License at:
 * http://www.opensource.org/licenses/mit-license.php
 *
 * @version 0.5.3
 */(function(a){a(function(){function g(a){return d.call(a)}function h(a,b){for(var c=0,d=a.length;c<d;++c)b(a[c])}function i(a,b){for(var c=a.length-1;c>=0;--c)b(a[c])}function k(){throw new Error("proceed() may only be called once")}function l(a,b){var c,d,e;this.target=a,this.func=b,this.aspects=[],c=this.orig=a[b],d=this,e=this.advised=function(){function j(b){var e=c.apply(a,b);return d._callSimpleAdvice("on",a,b),e}function k(b,c){d._callSimpleAdvice(b,a,c)}var a,e,f,h,i;a=this,e=g(arguments),h="afterReturning",d._callSimpleAdvice("before",a,e);try{f=d._callAroundAdvice(a,b,e,j)}catch(l){f=i=l,h="afterThrowing"}e=[f],k(h,e),k("after",e);if(i)throw i;return f},e._advisor=this}function m(a,b,c){var d=l.get(a,b);return d&&d.add(c)}function n(a,b,c){var d,e,f,g;d=[],g=0;while(f=b[g++])e=m(a,f,c),e&&d.push(e);return{remove:function(){for(var a=d.length-1;a>=0;--a)d[a].remove()}}}function o(a,b,c){var d,f;a=p(a);if(e(b))f=n(a,b,c);else{d=typeof b;if(d==="string")typeof a[b]=="function"&&(f=m(a,b,c));else if(d==="function")f=n(a,b(a),c);else for(var g in a)typeof a[g]=="function"&&b.test(g)&&(f=m(a,g,c))}return f}function p(a){return a.prototype||a}function q(a){return function(b,c,d){var e={};return e[a]=d,o(b,c,e)}}var a,b,c,d,e,f;f=Object.freeze||function(a){return a},a=Array.prototype,b=a.unshift,c=a.push,d=a.slice,e=Array.isArray||function(a){return Object.prototype.toString.call(a)=="[object Array]"};var j={before:i};return j.on=j.afterReturning=j.afterThrowing=j.after=h,l.prototype={_callSimpleAdvice:function(a,b,c){var d=j[a];d(this.aspects,function(d){var e=d[a];e&&e.apply(b,c)})},_callAroundAdvice:function(a,b,c,d){function i(b,c){var e;while(b>=0&&(e=h[b])&&typeof e.around!="function")--b;return b<0?d.call(a,c):j(e.around,b,c)}function j(c,d,e){var h,j;return h=function(a){return h=k,i(d-1,a)},j=f({target:a,method:b,args:e,proceed:function(){return h(arguments.length>0?g(arguments):e)}}),c.call(a,j)}var e,h;return h=this.aspects,e=h.length,i(e-1,c)},add:function(a){var b,c;return c=this,b=c.aspects,b.push(a),{remove:function(){for(var d=b.length;d>=0;--d)if(b[d]===a){b.splice(d,1);break}b.length||c.remove()}}},remove:function(){delete this.advised._advisor,this.target[this.func]=this.orig}},l.get=function(a,b){if(b in a){var c,d;d=a[b];if(typeof d!="function")throw new Error("Advice can only be applied to functions: "+b);return c=d._advisor,c||(c=new l(a,b),a[b]=c.advised),c}return},{add:o,before:q("before"),around:q("around"),on:q("on"),afterReturning:q("afterReturning"),afterThrowing:q("afterThrowing"),after:q("after")}})})(typeof define=="function"?define:function(a){typeof module!="undefined"?module.exports=a():this.aop=a()});