/** @license MIT License (c) copyright B Cavalier & J Hann *//**
 * wire/base plugin
 * Base wire plugin that provides properties, init, and destroy facets, and
 * a proxy for plain JS objects.
 *
 * wire is part of the cujo.js family of libraries (http://cujojs.com/)
 *
 * Licensed under the MIT License at:
 * http://www.opensource.org/licenses/mit-license.php
 */(function(a){a(["when"],function(a){function f(){}function g(a){return f.prototype=a,new f}function h(c,d,e,f){return a(f(e),function(a){return d.invoke(c,b.call(a)=="[object Array]"?a:[a])})}function i(a,b){var c=a.options;if(typeof c=="string")return h(c,a,[],b);var e,f;e=[];for(f in c)e.push(h(f,a,c[f],b));return d(e)}function j(a,b){a.resolve(b.literal)}function k(b,d,e){var f,g;f=d.prototype,g=typeof f=="string"?e.resolveRef(f):e(f),a(g,function(a){var d=c(a);b.resolve(d)},b.reject)}function l(a,b,c){var e,f,g;f=[],e=b.options;for(g in e)f.push(m(b,g,e[g],c));d(f,a.resolve,a.reject)}function m(b,c,d,e){var f=e(d,c,b.path);return a(f,function(a){b.set(c,a)}),f}function n(a,b,c){e(i(b,c),a)}function o(a){return{get:function(b){return a[b]},set:function(b,c){return a[b]=c,c},invoke:function(b,c){return typeof b=="string"&&(b=a[b]),b.apply(a,c)},destroy:function(){}}}function p(a,b){return b()}var b,c,d,e;return b=Object.prototype.toString,d=a.all,e=a.chain,c=Object.create||g,{wire$plugin:function(b,c){function e(a,b,c){d.push(function(){return i(b,c)}),a.resolve()}var d=[];return a(c,function(){a.reduce(d,p,{})}),{factories:{literal:j,prototype:k},facets:{properties:{configure:l},init:{initialize:n},ready:{ready:n},destroy:{ready:e}},proxies:[o]}}}})})(typeof define=="function"?define:typeof module!="undefined"?function(a,b){module.exports=b.apply(this,a.map(function(a){return require(a)}))}:function(a,b){this.wire_base=b(this.when)});