// Generated by LiveScript 1.2.0
(function(){
  var FEETPERMILE, EARTHRADIUS, RADIANSPERMILE;
  window.log = function(){
    return console.log.apply(console, arguments);
  };
  FEETPERMILE = 5280;
  EARTHRADIUS = 3959;
  RADIANSPERMILE = 1 / EARTHRADIUS;
  $('input').on('keypress', function(it){
    if (it.key === 'Enter') {
      return calculate();
    }
  });
  $('#btnCalculate').on('click', calculate);
  function calculate(){
    var h0, d0, d1;
    h0 = getVal('h0');
    d0 = getVal('d0');
    d1 = getHorizonDistance(h0);
    $('#d1').text(d1);
    return $('#h1').text(getTargetHiddenHeight(d0, d1));
  }
  function getHorizonDistance(h0){
    var rVert, theta;
    rVert = EARTHRADIUS - ftToMiles(h0);
    theta = Math.acos(rVert / EARTHRADIUS);
    return theta / RADIANSPERMILE;
  }
  function getTargetHiddenHeight(d0, d1){
    var rads, rVert;
    if (d0 < d1) {
      return 0;
    }
    rads = (d1 - d0) * RADIANSPERMILE;
    rVert = EARTHRADIUS * Math.cos(rads);
    return (EARTHRADIUS - rVert) * FEETPERMILE;
  }
  function ftToMiles(it){
    return it / FEETPERMILE;
  }
  function getVal(it){
    return parseFloat($("#" + it).val());
  }
}).call(this);
