// Generated by LiveScript 1.2.0
(function(){
  var FEETPERMETRE, MILESPERKM, EARTHRADIUSKM, UNITS, units;
  window.log = function(){
    return console.log.apply(console, arguments);
  };
  FEETPERMETRE = 3.2808;
  MILESPERKM = 0.621371192237;
  EARTHRADIUSKM = 6371;
  UNITS = {
    imperial: {
      minor: {
        name: 'feet',
        factor: 1 / FEETPERMETRE,
        'switch': FEETPERMETRE
      },
      major: {
        name: 'miles',
        factor: 1 / MILESPERKM,
        'switch': MILESPERKM
      }
    },
    metric: {
      minor: {
        name: 'metres',
        factor: 1,
        'switch': 1 / FEETPERMETRE
      },
      major: {
        name: 'km',
        factor: 1,
        'switch': 1 / MILESPERKM
      }
    }
  };
  initialiseUnits('imperial');
  calculate();
  $('input').on('keypress', function(it){
    if ((it.key || it.keyIdentifier) === 'Enter') {
      return calculate();
    }
  });
  $('#btnCalculate').on('click', calculate);
  $('#metric,#imperial').on('click', function(it){
    return switchUnits(it.target.value);
  });
  function calculate(){
    var h0, d0, h0_km, d0_km, d1_km, h1_m, d1, h1;
    h0 = getVal('h0');
    d0 = getVal('d0');
    h0_km = h0 * units.minor.factor * 0.001;
    d0_km = d0 * units.major.factor;
    d1_km = getHorizonDistance_km(h0_km);
    h1_m = getTargetHiddenHeight_km(d0_km - d1_km) * 1000;
    d1 = d1_km / units.major.factor;
    h1 = h1_m / units.minor.factor;
    $('#d1').text(d1);
    return $('#h1').text(h1);
  }
  function getHorizonDistance_km(h0_km){
    return Math.sqrt(Math.pow(h0_km, 2) + 2 * EARTHRADIUSKM * h0_km);
  }
  function getTargetHiddenHeight_km(d2_km){
    if (d2_km < 0) {
      return 0;
    }
    return Math.sqrt(Math.pow(d2_km, 2) + Math.pow(EARTHRADIUSKM, 2)) - EARTHRADIUSKM;
  }
  function getVal(it){
    return parseFloat($("#" + it).val());
  }
  function showUnits(it){
    $('.unit-minor .unit').text(it.minor.name);
    return $('.unit-major .unit').text(it.major.name);
  }
  function initialiseUnits(it){
    units = UNITS[it];
    $("input#" + it).prop('checked', true);
    return showUnits(units);
  }
  function switchUnits(it){
    showUnits(units = UNITS[it]);
    $('#h0').val(units.minor['switch'] * getVal('h0'));
    $('#d0').val(units.major['switch'] * getVal('d0'));
    return calculate();
  }
}).call(this);
