// Generated by LiveScript 1.4.0
(function(){
  var DEFAULTINS;
  window.log = function(){
    return console.log.apply(console, arguments);
  };
  DEFAULTINS = {
    d: 1.1,
    dl: 1.5,
    l_o: 1,
    l_s: 1,
    m_s: 0.9,
    nb: true,
    nu: 0.46,
    T_max: 1000,
    uy: 0.1,
    x: 250
  };
  $('input').on('change', function(){
    return calculate();
  });
  $('#nb').on('change', function(){
    return setRho_wAccess();
  });
  $('.help-btn').on('click', function(){
    return $(this).parents('.help').toggleClass('open closed');
  });
  populateIns(getInsByQuerystring());
  setRho_wAccess();
  calculate();
  function calculate(){
    var ins, outs, k, v;
    ins = {};
    $('input[type="checkbox"]').each(function(){
      return ins[$(this).attr('id')] = $(this).prop('checked');
    });
    $('input[type="text"]').each(function(){
      return ins[$(this).attr('id')] = parseFloat($(this).val());
    });
    outs = window.calc(ins);
    for (k in outs) {
      v = outs[k];
      v = Math.round(v * Math.pow(10, 4)) / Math.pow(10, 4);
      $("#" + k + ", ." + k).text(v).val(v);
      if (ins[k]) {
        ins[k] = v;
      }
    }
    return setQuerystringByIns(ins);
  }
  function getInsByQuerystring(){
    var ins, qs, k, v;
    ins = DEFAULTINS;
    qs = queryString.parse(location.search);
    for (k in qs) {
      v = qs[k];
      ins[k] = k === 'nb' ? v === 'true' : v;
    }
    return ins;
  }
  function populateIns(it){
    var k, v, t, $el, results$ = [];
    for (k in it) {
      v = it[k];
      t = ($el = $("#" + k)).attr('type');
      if (t === 'checkbox') {
        results$.push($el.prop('checked', v));
      } else {
        results$.push($el.val(v));
      }
    }
    return results$;
  }
  function setRho_wAccess(){
    return $('#rho_w').prop('disabled', $('#nb').prop('checked'));
  }
  function setQuerystringByIns(it){
    var qs;
    qs = queryString.stringify(it);
    return history.replaceState(void 8, "", "?" + qs);
  }
}).call(this);
