// Generated by LiveScript 1.4.0
(function(){
  var DEFAULTINS;
  window.log = function(){
    return console.log.apply(console, arguments);
  };
  DEFAULTINS = {
    d: 1200,
    d_T: 1186,
    dl: 6,
    l_o: 1,
    l_s: 300,
    m_s: 330,
    nb: true,
    T_max: 1000,
    uy: 0.1,
    v: 0,
    x: 226
  };
  $.ajax({
    url: 'package.json',
    success: function(it){
      return $('#version').text("v" + it.version);
    }
  });
  $('#reset').on('click', function(){
    return reset();
  });
  $('input').on('change', function(){
    return calculate();
  });
  $('#nb').on('change', function(){
    return setRho_wAccess();
  });
  $('.help .link').on('click', function(){
    return $(this).parents('.help').toggleClass('open closed');
  });
  populateIns(getInsByQuerystring());
  calculate();
  function calculate(){
    var ins, outs, k, v, $el;
    ins = {};
    $('input[type="checkbox"]').each(function(){
      return ins[$(this).attr('id')] = $(this).prop('checked');
    });
    $('input[type="text"]').each(function(){
      return ins[$(this).attr('id')] = parseFloat($(this).val());
    });
    outs = window.calc(ins);
    for (k in outs) {
      v = outs[k];
      $el = $("#" + k + ", ." + k);
      if (v.val != null) {
        $el.removeClass().addClass(v.alert ? 'alert' : void 8);
        v = v.val;
      }
      v = Math.round(v * Math.pow(10, 4)) / Math.pow(10, 4);
      $el.text(v).val(v);
      if (ins[k]) {
        ins[k] = v;
      }
    }
    return setQuerystringByIns(ins);
  }
  function getInsByQuerystring(){
    var ins, qs, k, v;
    ins = clone$(DEFAULTINS);
    qs = queryString.parse(location.search);
    for (k in qs) {
      v = qs[k];
      ins[k] = k === 'nb' ? v === 'true' : v;
    }
    return ins;
  }
  function populateIns(it){
    var k, v, t, $el;
    for (k in it) {
      v = it[k];
      t = ($el = $("#" + k)).attr('type');
      if (t === 'checkbox') {
        $el.prop('checked', v);
      } else {
        $el.text(v).val(v);
      }
    }
    return setRho_wAccess();
  }
  function reset(){
    populateIns(DEFAULTINS);
    return calculate();
  }
  function setQuerystringByIns(it){
    var qs;
    qs = queryString.stringify(it);
    return history.replaceState(void 8, "", "?" + qs);
  }
  function setRho_wAccess(){
    return $('#rho_w').prop('disabled', $('#nb').prop('checked'));
  }
  function clone$(it){
    function fun(){} fun.prototype = it;
    return new fun;
  }
}).call(this);
