// Generated by LiveScript 1.4.0
(function(){
  window.log = function(){
    return console.log.apply(console, arguments);
  };
  $('#d').val(1.005);
  $('#dl_i').val(0.79);
  $('#l').val(250);
  $('#l_i').val(253);
  $('#l_s').val(280);
  $('#m_s').val(224);
  $('#nu').val(0.46);
  $('#rho_l').val(975);
  $('#rho_w').val(1000);
  $('#T_max').val(1000);
}).call(this);
