// Generated by LiveScript 1.4.0
(function(){
  window.calc = function(it){
    var G, KGPERGRAM, METRESPERMM, MMPERMETRE, PI, r, a, v_s, rho_l, l, dlRatio, dd, r_T, a_T, v_sT, rho_lT, E, v1, b1, w1, f1, y;
    G = 9.81;
    KGPERGRAM = 0.001;
    METRESPERMM = 0.001;
    MMPERMETRE = 1000;
    PI = 3.14159265;
    r = METRESPERMM * it.d / 2;
    a = PI * Math.pow(r, 2);
    v_s = a * it.l_s;
    rho_l = KGPERGRAM * it.m_s / v_s;
    l = it.x + it.l_o;
    dlRatio = it.dl / l;
    dd = -it.nu * it.d * dlRatio;
    r_T = METRESPERMM * (it.d + dd) / 2;
    a_T = PI * Math.pow(r_T, 2);
    v_sT = a_T * it.l_s * (1 + dlRatio);
    rho_lT = KGPERGRAM * it.m_s / v_sT;
    E = it.T_max / (a * dlRatio);
    if (it.nb) {
      it.rho_w = rho_l;
    }
    v1 = a_T * 1;
    b1 = it.rho_w * v1 * G;
    w1 = rho_lT * v1 * G;
    f1 = w1 - b1;
    y = f1 * Math.pow(it.x, 2) / (8 * it.T_max);
    return {
      dd: dd,
      dl_percent: dlRatio * 100,
      E: E / Math.pow(10, 9),
      r: r * MMPERMETRE,
      rho_l: rho_l,
      rho_lT: rho_lT,
      rho_w: it.rho_w,
      y: y * MMPERMETRE
    };
  };
}).call(this);
